In [ ]:
import numpy as np

ajedrez = np.zeros((8,8), dtype=int)
ajedrez[::2, 1::2]=1 #todas las filas con saltos de 2 en 2
                        #y que tome a partir de la columna 1
                        #hasta el final con saltos de 2 en 2

print(ajedrez)

ajedrez[1::2, ::2]=1 #a partir de la primera fila con saltos de
                        # 2 en 2 y ademas para columnas pares que asigne 1
print(ajedrez)

[[0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
import numpy as np
arreglo1 = np.zeros(10)
print(arreglo1)

arreglo2 = np.ones(10)
print(arreglo2)

arreglo3=np.ones(10)*7

print(arreglo3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
