***sumar todos los elementos de una matriz***

In [ ]:
import numpy as np
x=np.array([[2,7,9],[3,2,4],[8,11,10]])
z=np.sum(x)
print(x)
print('la suma de sus elementos es: ', z)

[[ 2  7  9]
 [ 3  2  4]
 [ 8 11 10]]
la suma de sus elementos es:  56


***cree un objeto ndarray unidimensional con una longitud de 10 y todos 0, luego haga que el quinto elemento sea igual a 1***

In [ ]:
import numpy as np
x=np.zeros((1,10))
x[0,4]=1
print(x)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


***convertir en una lista python en un arreglo tipo numpy***

In [ ]:
import numpy as np
lista=[1,2,3,4,5,6]
print(type(lista))
print(lista)
arreglo=np.array(lista)
print(type(arreglo))
print(arreglo)

<class 'list'>
[1, 2, 3, 4, 5, 6]
<class 'numpy.ndarray'>
[1 2 3 4 5 6]
