25-8-2021

In [ ]:
#CNOOCER DIMENSIONES MATRIZ
import numpy as np

a=np.array([(1,2,3),(4,5,6)])
print(a)
print('dimensiones: ', a.ndim)
print('tipo de dato de la matriz:', a.dtype)
print('tamano de la matriz: ', a.size)
print('forma matriz', a.shape)
b=np.max(a)  #revisar si es cubo cuadrado o alargado, este es alargado
print('maximo', b)
print('minimo', np.min(a))
print(np.mean(a))

[[1 2 3]
 [4 5 6]]
dimensiones:  2
tipo de dato de la matriz: int64
tamano de la matriz:  6
forma matriz (2, 3)
maximo 6
minimo 1
3.5


In [ ]:
#cambiar forma de la matriz
b=np.array([(9,9,10),(11,12,13)])
print(b)
print('forma de la matriz', b.shape)
c=b.reshape(3,2)
print(c)


[[ 9  9 10]
 [11 12 13]]
forma de la matriz (2, 3)
[[ 9  9]
 [10 11]
 [12 13]]


In [ ]:
b=np.array([(8,9,10),(11,12,13)])
print(b)
print(b[0,2])
print(b[0:,2])
print(b[0,0:])
print(b[1,0:2])


[[ 8  9 10]
 [11 12 13]]
10
[10 13]
[ 8  9 10]
[11 12]


In [ ]:
ceros=np.zeros((4,6))
print(ceros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
estaturas=np.array([1.7,1.65,1.8,1.5,1.68])
print(estaturas)
print('dimensiones: ', estaturas.ndim)
print('tipo de dato de la matriz:', estaturas.dtype)
print('tamano de la matriz: ', estaturas.size)
print('forma matriz', estaturas.shape)
print('promedio de las estaturas es: ', estaturas.mean())  #promedio 
print('la estatura maxima es: ', estaturas.max())
print('la estatura minima es: ', estaturas.min())


[1.7  1.65 1.8  1.5  1.68]
dimensiones:  1
tipo de dato de la matriz: float64
tamano de la matriz:  5
forma matriz (5,)
promedio de las estaturas es:  1.666
la estatura maxima es:  1.8
la estatura minima es:  1.5


crear una matriz identidad, una matriz con valores que el usuario ingrese, y otra linea del valor 7. Luego realizar la suma de las 3 matrices. De la matriz resultante obtener el maximo, minimo y promedio

In [ ]:
#lea una matriz n x m. Para cada fila muestre el producto de los elementos. cuyo valor es un numero par
matriz1=[]
filas=3
columnas=3

#matriz identidad
identidad1=np.eye(3,3)
print('la matriz identidad es: ')
print(identidad1)

#llena de 7
completa=np.full((3,3),7)  #matriz 4x5 llena de el numero 7
print('la matriz de 7: ')
print(completa)

print('ingrese la matriz de 3x3 que desee:')
#se llena de 0 cada elemento de la matriz (encerar)
for i in range(filas):
    matriz1.append([0]*columnas)
print(matriz1)

#se pide cada elemento de la matriz
for f in range(filas):
  for c in range(columnas):
    matriz1[f][c]=int(input('ingrese el elemento '))

print(matriz1)

RES=completa+identidad1+matriz1
print('la suma de matrices: ')
print(RES)

#PROMEDio, max y min
print('promedio es: ', RES.mean())  #promedio 
print('maxima es: ', RES.max())
print('minima es: ', RES.min())


la matriz identidad es: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
la matriz de 7: 
[[7 7 7]
 [7 7 7]
 [7 7 7]]
ingrese la matriz de 3x3 que desee:
[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
ingrese el elemento 5
ingrese el elemento 4
ingrese el elemento 7
ingrese el elemento 7
ingrese el elemento 9
ingrese el elemento 7
ingrese el elemento 2
ingrese el elemento 3
ingrese el elemento 5
[[5, 4, 7], [7, 9, 7], [2, 3, 5]]
la suma de matrices: 
[[13. 11. 14.]
 [14. 17. 14.]
 [ 9. 10. 13.]]
promedio es:  12.777777777777779
maxima es:  17.0
minima es:  9.0
