In [ ]:
#Generar un arreglo  arr1 con 30 números que vayan del 6 al 20 (30 elementos). 
#Obtenga el promedio de los elementos del arreglo arr1. 
#Generar una matriz mat1 de 4 filas y 4 columnas llenada con el valor que resultó del promedio del arreglo arr1. 
#Sume los elementos de mat1
#Seleccione la respuesta correcta que da la suma

In [ ]:
import numpy as np
arr1=np.linspace(6,20,30) # el ultimo valor es el numero de elementos que se requieren
print(arr1)
promedio=arr1.mean()
print('el promedio es: ', promedio)
mat1=np.full((4,4),promedio)
print('Generar una matriz mat1 de 4 filas y 4 columnas llenada con el valor que resultó del promedio del arreglo')
print(mat1)
suma=np.sum(mat1)
print('Sume los elementos de mat1')
print(suma)

[ 6.          6.48275862  6.96551724  7.44827586  7.93103448  8.4137931
  8.89655172  9.37931034  9.86206897 10.34482759 10.82758621 11.31034483
 11.79310345 12.27586207 12.75862069 13.24137931 13.72413793 14.20689655
 14.68965517 15.17241379 15.65517241 16.13793103 16.62068966 17.10344828
 17.5862069  18.06896552 18.55172414 19.03448276 19.51724138 20.        ]
el promedio es:  13.000000000000002
Generar una matriz mat1 de 4 filas y 4 columnas llenada con el valor que resultó del promedio del arreglo
[[13. 13. 13. 13.]
 [13. 13. 13. 13.]
 [13. 13. 13. 13.]
 [13. 13. 13. 13.]]
Sume los elementos de mat1
208.00000000000003
